package main

import (
	"context"
	"errors"
	"log/slog"
	"os"

	"github.com/m0rjc/goconfig"
	"github.com/m0rjc/goconfig/example/structured_logging/config"
	"github.com/m0rjc/goconfig/example/structured_logging/logger"
)

func main() {
	// 1. Set up a structured logger
	err := logger.Init()
	defer logger.Close()
	if err != nil {
		slog.Error("Failed to initialise structured logger", "error", err)
		// Exit(0) because the point of this demo is to show logging. The build pipeline requires a 0 exit code.
		os.Exit(0)
	}

	ctx := context.Background()
	cfg, err := config.Load(ctx)

	if err != nil {
		slog.Info("The following log is generated by the provided gocondfig.LogError fucntion")
		goconfig.LogError(slog.Default(), err, goconfig.WithLogMessage("config_error"))

		var configErrors *goconfig.ConfigErrors
		if errors.As(err, &configErrors) {
			slog.Info("The following log is generated by iterating over the errors manually")
			// 3. Log errors to structured log
			for _, e := range configErrors.Errors {
				slog.Error("Configuration error",
					"key", e.Key,
					"error", e.Err.Error(),
				)
			}
			// The purpose of this demo is to show logging. Exit(0) for an expected error.
			slog.Info("This error was expected. The program will exit successfully to allow build pipelines to pass.")
			os.Exit(0)
		} else {
			slog.Error("This error was unexpected. The program will exit with an error code to fail build pipelines.")
			os.Exit(1)
		}
	}

	// 4. Show success (won't reach here in this example)
	slog.Info("Configuration loaded successfully",
		"host", cfg.Host,
		"port", cfg.Port,
		"database", cfg.Database,
	)
}
