package main

import (
	"context"
	"errors"
	"log/slog"
	"os"

	"github.com/m0rjc/goconfig"
	"github.com/m0rjc/goconfig/example/structured_logging/config"
)

func main() {
	// 1. Set up a structured logger
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))
	slog.SetDefault(logger)

	// 2. Set up environment that will fail constraints
	// DB_HOST is missing (mandatory)
	os.Setenv("DB_PORT", "80")         // fails min:1024
	os.Setenv("DB_USER", "admin")      // valid
	os.Setenv("DB_PASS", "short")      // fails pattern: ^.{8,}$
	os.Setenv("DB_NAME", "production") // valid
	os.Setenv("DB_TIMEOUT", "500")     // fails max:300

	ctx := context.Background()
	cfg, err := config.Load(ctx)

	if err != nil {
		logger.Info("The following log is generated by the provided gocondfig.LogError fucntion")
		goconfig.LogError(logger, err, goconfig.WithLogMessage("config_error"))

		var configErrors *goconfig.ConfigErrors
		if errors.As(err, &configErrors) {
			logger.Info("The following log is generated by iterating over the errors manually")
			// 3. Log errors to structured log
			for _, e := range configErrors.Errors {
				slog.Error("Configuration error",
					"key", e.Key,
					"error", e.Err.Error(),
				)
			}
			// The purpose of this demo is to show logging. Exit(0) for an expected error.
			logger.Info("This error was expected. The program will exit successfully to allow build pipelines to pass.")
			os.Exit(0)
		} else {
			logger.Error("This error was unexpected. The program will exit with an error code to fail build pipelines.")
			os.Exit(1)
		}
	}

	// 4. Show success (won't reach here in this example)
	slog.Info("Configuration loaded successfully",
		"host", cfg.Host,
		"port", cfg.Port,
		"database", cfg.Database,
	)
}
